travis:
  secure:
    BINSTAR_TOKEN: emHabiPsNuCBUs97qoxtcPXg+YzkH4qXI0Ei90NWJH+z1R7tE4S950MNcnKkCXVYke5rHWYphibOd20ZN+vfqd3UBMH41cyxY2JvhP12a5H0zTnWbLDuFmA240EHCVYHEXXEs7QPU2oona8VXVqIRWbtafEHPdEAAPKnDDn1NTkSN+/CH43szXd/uc+zSw3Uo7V7sRjGk/AAJcD7xJo9ECF7XEytj1wPs3wyHU4v7dsVQPclRJCx7qV2tcOQfJaRWm/vKYvDXmHgGzxiPL/mcTqr6PN3cT78cCYudcUm41sVCdDBJlI4PmivVP7kwFKZFbt30IVwLM9AM80t9R7wXeFVzKwdA3T5J/Cj7MaKEDSvE6JkizaTFHtly+jsX4ZXzNvPsvcqvwpFlnvKRsDeggpfkEJ010X7i06VrdgDKsVyi7NPMmYbjpsw7MTznRDF/WvqYBfyEYSQ9tX6B7xG3DU3UWFVrvVOgmjJu95sYMeUvYEQjoBaMYkp+eKdBaz58UgNuW/vfUaj/x+/QGZgtc0hJ7RjBWmZxbKcEoJ1TGpn2XCrwe+uDYIGRMI8V73rE8z9JJMRj2C/ZPPyCEnjVavHS+OyXQ0lg2DoEC2e6dVtldlk5Ra1tKCNDlsMAJtjXWp0Dr2KVNCF4I45M3qW6josYxmIfDCvYegaFPMRzyk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
